eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9800/eureka/
server:
  port: 9831
spring:
  application:
    name: zuul-web
zuul:
  routes:
    api-1:
      path: /user-service/**
      serviceId: user-service
    api-2:
      path: /log-service/**
      serviceId: log-service