server:
  port: 9810
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9800/eureka/
  #表示将自己的ip注册到Eureka Server上，如果是false的话会显示hostname而不是ip地址
  instance:
    prefer-ip-address: true
ribbon-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule